image: Visual Studio 2019

environment:
  host: x86_64-pc-windows-msvc
  matrix:
    - platform: x86_64
      target: x86_64-pc-windows-msvc
      channel: stable
    - platform: arm64
      target: aarch64-pc-windows-msvc
      channel: nightly
matrix:
  allow_failures:
    - platform: arm64

install:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - appveyor DownloadFile https://people.xiph.org/~tdaede/nasm-2.14.02-win64.zip -FileName nasm.zip
    - appveyor DownloadFile https://github.com/mozilla/sccache/releases/download/0.2.8/sccache-0.2.8-x86_64-pc-windows-msvc.tar.gz
    - tar xzf sccache-0.2.8-x86_64-pc-windows-msvc.tar.gz
    - 7z e -y nasm.zip
    - rustup-init -yv --default-toolchain %channel% --default-host %host%
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin;%APPVEYOR_BUILD_FOLDER%;nasm-2.14.02;sccache-0.2.8-x86_64-pc-windows-msvc
    - set RUSTC_WRAPPER=sccache
    - set SCCACHE_CACHE_SIZE=500M
    - set SCCACHE_DIR=%LOCALAPPDATA%\Mozilla\sccache
    - ps: $Env:PKG_CONFIG_ALLOW_CROSS=1
    - rustc -vV
    - cargo -vV
    - rustup target add %target%

on_success:
    - sccache -s

cache:
    - '%LOCALAPPDATA%\Mozilla\sccache'

build_script:
    - cargo build --release --target=%target%

test_script:
    - cargo test --target=%target% --verbose

artifacts:
    - path: target\$(target)\release\rav1e.exe
      name: rav1e-$(platform)
      
deploy:
  - provider: GitHub
    artifact: target\$(target)\release\rav1e.exe
    auth_token:
      secure: 'LPBjNyFOg+vBkVR4w+89YVNhByaXBGNwtN6UwkFkWTfPow5oeCbFMtJavU9ZLs+c'
    prerelease: true
    on:
      appveyor_repo_tag: true
