# rustfmt configuration, only used for some files

max_width = 79
comment_width = 79
force_explicit_abi = false
fn_args_density = "Compressed"
use_small_heuristics = "Off"
match_arm_blocks = false
reorder_imports = true
tab_spaces = 4
use_field_init_shorthand = true
trailing_comma = "Never"
ignore = [
    "build.rs",
    "src/context.rs", # Partial
    # "src/ec.rs", # Clean
    "src/lib.rs", # Did not clean yet to avoid conflicts with open PRs.
    # "src/partition.rs", # Clean
    # "src/plane.rs", # Clean
    # "src/predict.rs", # Clean
    # "src/quantize.rs", # Clean
    # "src/rdo.rs", # Clean
    # "src/transform.rs", # Clean
    # "benches/bench.rs", # Clean
    # "src/bin/rav1e.rs", # Clean
    # "src/bin/rav1repl.rs", # Clean
    "tests/aom.rs",
]
